config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'food_trucks#home'

  resources :food_trucks, only: [:index, :show, :new, :create, :edit, :update] do
    resources :reservations, only: [:new, :create, :show] do
      get 'payments/new', to: 'payments#new'
      get 'payments/paid', to: 'payments#paid'
    end
  end
  resources :reservations, only: [:index, :update]
end

app/models/food_truck.rb
class FoodTruck < ApplicationRecord
  CATEGORIES = ["italian", "turkish", "belgian", "chinese", "japanese", "french", "burgers", "vegan"]

  mount_uploader :photo, PhotoUploader
  monetize :price_cents

  has_many :reservations, dependent: :destroy
  belongs_to :user
  validates :name, presence: true, uniqueness: true

  validates :category, inclusion: { in: CATEGORIES }
  validates :price, presence: true

  validates :city, presence: true
end

app/controllers/food_trucks_controller.rb
class FoodTrucksController < ApplicationController
  before_action :set_foodtruck, only: [:show, :edit, :update]
  before_action :skip_pundit?, only: :home
  skip_before_action :authenticate_user!, only: [:index, :show, :home]

  def home
  end

  def index
    if params[:query].present?
      sql_query = " \
        food_trucks.name ILIKE :query \
        OR food_trucks.category ILIKE :query \
        OR food_trucks.city ILIKE :query \
      "
      @foodtrucks = policy_scope(FoodTruck).where(sql_query, query: "%#{params[:query]}%").order(created_at: :desc)
        if @foodtrucks.empty?
          flash[:alert] = "Couldn't find your search !"
          redirect_to root_path
        else
          @foodtrucks
        end
    else
      @foodtrucks = policy_scope(FoodTruck).order(created_at: :desc)
    end
  end

  def new
    @foodtruck = FoodTruck.new
    authorize @foodtruck
  end

  def create
    @foodtruck = FoodTruck.new(foodtruck_params)
    @foodtruck.user = current_user
    if @foodtruck.save
      redirect_to food_truck_path(@foodtruck)
    else
      render 'new'
    end

    authorize @foodtruck
  end

  def show
    authorize @foodtruck
    @reservation = Reservation.new
  end

  def edit
    authorize @foodtruck
  end

  def update
    if @foodtruck.update(foodtruck_params)
      redirect_to food_truck_path(@foodtruck)
      flash[:notice] = 'Food Truck updated'
    else
      render :edit
      flash.now[:alert] = 'Food truck not updated !'
    end
    authorize @foodtruck
  end

  private

  def foodtruck_params
    params.require(:food_truck).permit(:name, :category, :price_cents, :city, :description, :photo, :search)
  end

  def set_foodtruck
    @foodtruck = FoodTruck.find(params[:id])
  end
end

app/views/food_trucks/edit.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-8 center-block">
      <div class="container">
        <div class="column">
          <div class="card" style="width: 100%; height: 566px;">
            <div class="food-truck-image" style="max-height:465px;">
              <%= simple_form_for @foodtruck do |f| %>
                <% if @foodtruck.photo.present? %>
                  <%= cl_image_tag @foodtruck.photo, crop: :fill, height: 465, class: "card-img-top" %>
                <% else %>
                  <%= cl_image_tag "generic_l79l58",crop: :fill, height: 465, class: "card-img-top" %>
                <% end %>
                <%= f.input :description, style: 'margin-top:-20px' %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="container">
        <div class="column center-block">
          <div class="col-sm">
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <div class="label"></div> <div class="text-box"><%= f.input :name %></div>
          </div>
          <div class="col-sm ">
            <div class="label"></div> <div class="text-box"> <%= f.input :city %></div>
          </div>
          <div class="col-sm ">
            <div class="label"></div> <div class="text-box"><%= f.input :category, collection: FoodTruck::CATEGORIES %></div>
          </div>
          <div class="col-sm ">
            <div class="label"></div>  <div class="text-box">  <%= f.input :price_cents, label: 'Price' %></div>
          </div>
          <div class="col-sm">
               <%= f.submit "Submit", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/food_trucks/home.html.erb
<div class="banner" style="background-image: url('https://images.unsplash.com/photo-1500338427510-5deb175987d2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1654&q=80');">>
  <h1>Food Truckr</h1>
</div>

<h2 class="mt-3 row justify-content-center" style="margin-right: 0; margin-left: 0;">See Food trucks around you!</h2>

<div class="index container mt-3">
  <div class="cards">
    <div class="row">
      <% FoodTruck::CATEGORIES.each do |category| %>
        <% url = cl_image_path category %>
      <div class="col-4">
        <%= link_to food_trucks_path(query: category) do %>
          <div class="card-category my-2", id="foodtruck-card", style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= url %>')">
            <%= "#{category.capitalize} (#{FoodTruck.where(category: category).count})" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/food_trucks/index.html.erb
<div class="d-flex justify-content-between align-items-center mx-5">
  <%= link_to "back", :back, class: 'btn btn-primary' %>
  <h2 class="mt-3 row justify-content-center">Food Trucks</h2>
  <h2></h2>
</div>

<div class="index container mt-3">
  <div class="cards">
    <div class="row">
    <% @foodtrucks.each do |foodtruck| %>
      <% if foodtruck.photo.present? %>
        <% url = cl_image_path foodtruck.photo, height: 300, width: 300, crop: :fill %>
      <% else %>
        <% url = cl_image_path "generic_l79l58", height: 300, width: 300, crop: :fill %>
    <% end %>
      <div class="col-6">

        <%= link_to food_truck_path(foodtruck), class: "text-decoration-none text-reset" do %>
          <div class="card-product">
            <img src="<%= url %>" />
            <div class="card-product-infos">
              <h2><%= foodtruck.name %></h2>
              <p><%= foodtruck.description %></p>
              <p><%= foodtruck.city %></p>
              <p><%= foodtruck.price_cents %> CHF</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/food_trucks/new.html.erb
<div class="container mb-3" style="width: 600px">
  <div class="text-box" style="width: 600px">
    <h2 class="my-3" style="text-align:center">Create Your Food Truck</h2>
    <%= render 'shared/form' %>
  </div>
</div>

app/views/food_trucks/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-8 center-block">
      <div class="container">
        <div class="column">
          <div class="card" style="width: 100%; height: 566px;">
            <div class="food-truck-image" style="max-height:465px;">
              <% if @foodtruck.photo.present? %>
                <%= cl_image_tag @foodtruck.photo, crop: :fill, height: 465, class: "card-img-top" %>
              <% else %>
                <%= cl_image_tag "generic_l79l58",crop: :fill, height: 465, class: "card-img-top" %>
              <% end %>
            </div>
            <p class="card-text p-3">
              <%= @foodtruck.description %>
              <% if policy(@foodtruck).edit? %>
                <%= link_to edit_food_truck_path(@foodtruck), class: 'ml-3' do %>
                  <i class="fas fa-pencil-alt fa-lg mr-3"></i>
                <% end %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="container">
        <div class="column center-block">
          <div class="col-sm">
            <div class="label">name :</div> <div class="text-box"><%= @foodtruck.name %></div>
          </div>
          <div class="col-sm ">
            <div class="label">city :</div> <div class="text-box"><%= @foodtruck.city %></div>
          </div>
          <div class="col-sm ">
            <div class="label">category :</div> <div class="text-box"><%= @foodtruck.category %></div>
          </div>
          <div class="col-sm ">
            <div class="label">price :</div>  <div class="text-box"> <%= "#{humanized_money(@foodtruck.price_cents)} #{@foodtruck.price_currency}" %></div>
          </div>
          <div class="col-sm">

          </div>
          <div class="col-sm mt-3">
            <%= simple_form_for [@foodtruck, @reservation] do |f| %>
            <%= f.input :checkin_date, order: [:day, :month, :year], :default => Date.today %>
            <%= f.input :checkout_date, order: [:day, :month, :year], :default => Date.today + 1 %>
            <div class="d-flex justify-content-between">
              <%= f.button :submit, class: "btn btn-primary" %>
              <%= link_to "back", :back, class: 'btn btn-primary' %>
            </div>
           <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>