config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'food_trucks#home'

  resources :food_trucks, only: [:index, :show, :new, :create, :edit, :update] do
    resources :reservations, only: [:new, :create, :show] do
      get 'payments/new', to: 'payments#new'
      get 'payments/paid', to: 'payments#paid'
    end
  end
  resources :reservations, only: [:index, :update]
end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer brings <i class="fas fa-heart"></i> from Food Truckr
  </div>
</div>

app/views/shared/_form.html.erb
<div class="container">
  <%= simple_form_for @foodtruck do |f| %>
    <%= f.input :name %>
    <%= f.input :category, collection: FoodTruck::CATEGORIES %>
    <%= f.input :price_cents, label: 'Price (CHF per day)' %>
    <%= f.input :city %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= form_tag food_trucks_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      placeholder: "Find a Food Truck",
      style: "height:40px" %>
    <%= submit_tag "Search", class: "btn btn-primary"%>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached?%>
            <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://cdn.pixabay.com/photo/2014/04/02/10/25/man-303792_960_720.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Add a new food truck", new_food_truck_path, class: "dropdown-item" %>
            <%= link_to "My Reservations", reservations_path, class: "dropdown-item" %>
            <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item d-flex">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>