config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'food_trucks#home'

  resources :food_trucks, only: [:index, :show, :new, :create, :edit, :update] do
    resources :reservations, only: [:new, :create, :show] do
      get 'payments/new', to: 'payments#new'
      get 'payments/paid', to: 'payments#paid'
    end
  end
  resources :reservations, only: [:index, :update]
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  monetize :amount_cents

  belongs_to :user
  belongs_to :food_truck
  validates :checkin_date, presence: true
  validates :checkout_date, presence: true
  validate :forbids_owner_booking

  private

  def forbids_owner_booking
    errors.add(:user_id, "You cannot book your own Food Truck!") if user_id == food_truck.user_id
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @foodtruck = FoodTruck.find(params[:food_truck_id])
    @reservation = Reservation.new
  end

  def create
    @foodtruck = FoodTruck.find(params[:food_truck_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.food_truck = @foodtruck
    @reservation.amount_cents = @foodtruck.price_cents

    if @reservation.checkout_date > @reservation.checkin_date && @reservation.save
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [{
          name: @foodtruck.name,
          amount: @foodtruck.price_cents * 100,
          currency: 'CHF',
          quantity: (@reservation.checkout_date - @reservation.checkin_date).to_i
        }],
        success_url: food_truck_reservation_payments_paid_url(@foodtruck, @reservation),
        cancel_url: reservations_url
      )

      @reservation.update(checkout_session_id: session.id)
      redirect_to reservations_path
    else

      if @reservation.errors.any?
        flash[:alert] = @reservation.errors.messages[:user_id].join
      end
      if @reservation.checkout_date <= @reservation.checkin_date
        flash[:alert] = "Checkout date must be later than Checkin date!"
      end
      redirect_to food_truck_path(@foodtruck.id)

    end
  end

  def index
    @userreservations = Reservation.where(user_id: current_user.id)
    @ownerreservations = Reservation.joins(:food_truck).where("food_trucks.user_id = #{current_user.id}")
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.accepted_at.nil?
      @reservation.accepted_at = Time.now
    else
      @reservation.paid_at = Time.now
    end
    @reservation.save
    redirect_to reservations_path
    flash.now[:notice] = 'Booked'
  end

  def show
    @reservation = current_user.reservations.find(params[:id])
  end

  private

  def reservation_params
    params.require(:reservation).permit(:checkin_date, :checkout_date)
  end
end

app/views/reservations/index.html.erb
<script src="https://js.stripe.com/v3/"></script>
<div class="banner" style="background-image: url('https://images.unsplash.com/photo-1533229613598-751dc97ec35f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80')">
  <h1>Your bookings</h1>
</div>

<% if @userreservations.present? %>
  <h2 class="mt-3 row justify-content-center">So far you have booked</h2>

  <div class="index container mt-3">
    <div class="cards">
      <div class="row">
        <% @userreservations.each do |reservation| %>

          <% if reservation.food_truck.photo.present? %>
            <% url = cl_image_path reservation.food_truck.photo, height: 300, width: 300, crop: :fill %>
          <% else %>
            <% url = cl_image_path "generic_l79l58", height: 300, width: 300, crop: :fill %>
          <% end %>

          <div class="col-12">
            <div class="card-booking">
              <img src="<%= url %>" />

              <div class="card-booking-infos text-center">
                <div class="booking title"><%= reservation.food_truck.name %></div>
                <div class="booking-info">
                  <div><%= "checkin date : #{reservation.checkin_date.strftime("%m/%d/%Y at %I:%M%p")}" %></div>
                  <div><%= "checkout date : #{reservation.checkout_date.strftime("%m/%d/%Y at %I:%M%p")}"  %></div>
                  <div><%= "price: #{reservation.food_truck.price * 100} CHF" %></div>

                  <% if reservation.accepted_at == nil%>
                    <div class="booking_cards_nay p-2 bd-highlight"><%="Not accepted yet"%></div>
                  <% elsif reservation.accepted_at != nil && reservation.paid_at == nil%>
                    <button type="button" class="btn btn-primary" onclick="Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>').redirectToCheckout({sessionId: '<%= reservation.checkout_session_id %>'})">I pay now</button>
                  <% else %>
                    <div class="booking_cards_p p-2 bd-highlight"><%=reservation.paid_at.strftime("Paid on %m/%d/%Y at %I:%M%p ")%></div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <%end %>
      </div>
    </div>
  </div>
<% else %>
  <h2 class="mt-3 row justify-content-center">No bookings yet</h2>
<% end %>

<% if @ownerreservations.present? %>
  <h2 class="mt-3 row justify-content-center">Your Food Truck(s) bookings</h2>

  <div class="index container mt-3">
    <div class="cards">
      <div class="row">
        <% @ownerreservations.each do |reservation| %>

          <% if reservation.food_truck.photo.present? %>
            <% url = cl_image_path reservation.food_truck.photo, height: 300, width: 300, crop: :fill %>
          <% else %>
            <% url = cl_image_path "generic_l79l58", height: 300, width: 300, crop: :fill %>
          <% end %>

          <div class="col-12">
            <div class="card-booking">
              <img src="<%= url %>" />

              <div class="card-booking-infos text-center">
                <div class="booking title"><%= reservation.user.email %></div>
                <div class="booking-info">

                  <div><%= reservation.food_truck.name%></div>
                  <div><%= "checkin date : #{reservation.checkin_date.strftime("%m/%d/%Y at %I:%M%p")}" %></div>
                  <div><%= "checkout date : #{reservation.checkout_date.strftime("%m/%d/%Y at %I:%M%p")}"  %></div>
                  <div><%= "price: #{reservation.food_truck.price * 100} CHF" %></div>

                  <% if reservation.accepted_at == nil%>
                    <%= link_to "Accept the booking", reservation_path(reservation.id), method: :patch, class: "btn btn-success"%>
                  <% elsif reservation.accepted_at != nil && reservation.paid_at == nil%>
                    <div class="booking_cards_npy p-2 bd-highlight"><%="Not paid yet"%></div>
                  <% else %>
                    <div class="booking_cards_p p-2 bd-highlight"><%="Paid by #{reservation.user.email} on #{reservation.paid_at.strftime("%m/%d/%Y at %I:%M%p ")}"%></div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/reservations/show.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @reservation.food_truck.photo_url, width: '100%' %></div>
    <div class="col">
      <h1>Order #<%= @reservation.id %> <small><span class="badge badge-primary"><%= @reservation.state %></span></small></h1>
      <ul class="list-unstyled">
        <li><strong>ISSUED ON</strong> <%= @reservation.created_at.to_date %></li>
        <li><strong>TEDDY</strong> <%= @reservation.food_truck.name %></li>
        <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @reservation.amount_cents %></li>
        </li>
      </ul>
      <p>Estimated delivery in <strong>2 business days</strong></p>
    </div>
  </div>
</div>